-- Ex 1
CREATE USER User_A IDENTIFIED BY "pt3031616";
CREATE USER User_B IDENTIFIED BY "pt3031616";
CREATE USER User_C IDENTIFIED BY "pt3031616";
CREATE USER User_D IDENTIFIED BY "pt3031616";
CREATE USER User_E IDENTIFIED BY "pt3031616";

-- EX2
GRANT ALL PRIVILEGES ON university.* User_A WITH GRANT OPTION;
REVOKE ALL PRIVILEGES ON university.classroom FROM User_A;

-- EX3
SHOW GRANTS FOR User_A;